name: attendance_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # A testing library which makes it easy to test blocs. Built to be used with
  # the bloc state management package.
  bloc_test: ^9.1.7

  # Utilities for converting between data representations. Provides a number of
  # Sink, Codec, Decoder, and Encoder types.
  convert: ^3.1.1

  # Implementations of SHA, MD5, and HMAC cryptographic functions.
  crypto: ^3.0.5

  # Functional Programming in Dart. Purify your Dart code using
  # efficient immutable data structures, monads, lenses and other FP tools.
  dartz: ^0.10.1

  # A Dart package that helps to implement value based equality
  # without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic
  # Component) design pattern. Built to be used with the bloc state management
  # package.
  flutter_bloc: ^8.1.6

  # Simple direct Service Locator that allows to decouple the interface
  # from a concrete implementation and to access the concrete implementation
  # from everywhere in your App.
  get_it: ^7.7.0

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^1.2.2
  intercepted_client: ^0.0.1

  # Provides access to a wide variety of Google Fonts, allowing you to easily use custom fonts in your Flutter application.
  google_fonts: ^6.2.1

  # A persistence library for Flutter and Dart, providing an SQLite abstraction with a repository pattern.
  floor: ^1.5.0

  # The "geolocator" package provides easy access to the device's location
  # services. It supports retrieving the current position, listening for
  # location updates, and performing geocoding operations such as converting
  # coordinates into addresses and vice versa. This package is essential for
  # location-based features in your app.
  geolocator: ^12.0.0

  # The "provider" package is a popular state management solution for Flutter
  # applications. It enables you to manage and share state across different
  # parts of your app in a structured and scalable way, making it easier to
  # build responsive and maintainable user interfaces.
  provider: ^6.1.2

  # The "flutter_map" package provides a versatile and customizable map widget
  # for Flutter applications. It supports various map providers and features 
  # like markers, polygons, and interactive map controls, making it ideal for
  # displaying geographical data and implementing map-based features in your app.
  flutter_map: ^7.0.1

  geocoding: ^3.0.0

  # The "flutter_map_cancellable_tile_provider" package is an add-on for the
  # "flutter_map" package, providing a cancellable tile provider. This allows
  # map tiles to be cancelled while they are being loaded, which can improve
  # performance and resource management, especially when dealing with large
  # maps or when the map view changes rapidly.
  flutter_map_cancellable_tile_provider: ^3.0.0

  # The "latlong2" package is a simple library for representing and manipulating
  # geographical coordinates (latitude and longitude) in Flutter and Dart. It
  # provides utilities for calculating distances, bearings, and other
  # geospatial operations, making it useful for map-based applications.
  latlong2: ^0.9.1

  
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

   # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.12

  # The "floor_generator" package is part of the Floor ORM (Object-Relational
  # Mapping) library, which is used to generate the necessary code for managing
  # SQLite databases in Flutter projects. This package specifically handles the
  # code generation aspects for the Floor ORM.
  floor_generator: ^1.5.0

  # A mock framework inspired by Mockito with APIs for Fakes, Mocks,
  # behavior verification, and stubbing.
  mockito: ^5.4.4

  # A Dart mock library which simplifies mocking with null safety support and
  # no manual mocks or code generation.
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
